# This workflow will install Python dependencies, run tests and lint with a
# single version of Python. For more information see:
# https://help.github.com/actions/language-and-framework-guides\
# /using-python-with-github-actions

name: Build and commit documentation

on:
  push:
    branches: ["master"]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        run: |
          pip install --ignore-installed \
              git+https://github.com/legalsylvain/openupgradelib.git@legalsylvain-various-fixes-openupgrade-doc
          pip install sphinx
      - name: OpenUpgrade Docs
        run: |
          # try to build the documentation
          sh ./build_openupgrade_docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          cwd: "openupgrade"
          default_author: github_actions
          message: "[UPD] HTML documentation"
