# This workflow will install Python dependencies, run tests and lint with a
# single version of Python. For more information see:
# https://help.github.com/actions/language-and-framework-guides\
# /using-python-with-github-actions

name: Test - Build Documentation on new PR

on:
  pull_request:

jobs:
  documentation-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Current PR code
        uses: actions/checkout@v2

  call-task-documentation-build:
    uses: ./.github/workflows/task-build-documentation.yml
