name: Build and commit documentation - Schedule

on:
  schedule: # For Test Purpose: Schedule the job to run each 5 minutes
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  call-workflow-documentation-branch:
    uses: grap/openupgrade-doc-test/.github/workflows/documentation-commit.yml@documentation
